<!-- external javascript -->
<?php echo $this->Html->script('/webroot/admin-theme/bower_components/bootstrap/dist/js/bootstrap.min.js'); ?>
<?php echo $this->Html->script('/webroot/admin-theme/js/jquery.cookie.js'); ?> 
<?php echo $this->Html->script('/webroot/admin-theme/bower_components/moment/min/moment.min.js'); ?>
<?php echo $this->Html->script('/webroot/admin-theme/bower_components/fullcalendar/dist/fullcalendar.min.js'); ?>  
<?php echo $this->Html->script('/webroot/admin-theme/js/jquery.dataTables.min.js'); ?>  
<?php echo $this->Html->script('/webroot/admin-theme/bower_components/chosen/chosen.jquery.min.js'); ?>
<?php echo $this->Html->script('/webroot/admin-theme/bower_components/colorbox/jquery.colorbox-min.js'); ?> 
<?php echo $this->Html->script('/webroot/admin-theme/bower_components/responsive-tables/responsive-tables.js'); ?>
<?php echo $this->Html->script('/webroot/admin-theme/bower_components/bootstrap-tour/build/js/bootstrap-tour.min.js'); ?>
<?php echo $this->Html->script('/webroot/admin-theme/js/jquery.raty.min.js'); ?>
<?php echo $this->Html->script('/webroot/admin-theme/js/jquery.iphone.toggle.js'); ?>
<?php echo $this->Html->script('/webroot/admin-theme/js/jquery.autogrow-textarea.js'); ?>
<?php echo $this->Html->script('/webroot/admin-theme/js/jquery.uploadify-3.1.min.js'); ?>
<?php echo $this->Html->script('/webroot/admin-theme/js/jquery.history.js'); ?> 
<?php echo $this->Html->script('/webroot/admin-theme/js/charisma.js'); ?>
